# Generated by Django 4.1.2 on 2022-11-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0007_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product-images/default-dp.png', upload_to='product-images/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile-photos/default-dp.png', upload_to='profile-photos/%Y/%m/%D/'),
        ),
    ]
