# Generated by Django 4.1.2 on 2022-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0008_remove_user_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='end_of_bid',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product-images/stock-image.png', upload_to='product-images/%Y/%m/%D/'),
        ),
    ]
