# Generated by Django 4.1.2 on 2022-11-26 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_alter_bid_end_of_bid_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=4096, verbose_name='question')),
                ('answer', models.CharField(max_length=4096, verbose_name='answer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.product')),
                ('recipient', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
