# Generated by Django 4.1.3 on 2022-12-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='winner',
            new_name='bidder',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=4096, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sender',
            field=models.ForeignKey(db_constraint=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
