# Generated by Django 4.1.3 on 2022-12-08 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0012_bid_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='end_of_bid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='end_of_bid',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
