# Generated by Django 4.1.3 on 2022-12-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0014_alter_faq_recipient_alter_faq_sender'),
        ('auctionapp', '0014_bid_is_active_alter_faq_recipient'),
    ]

    operations = [
    ]
